### ISSUE TITLE
Account Settings

### ISSUE THREAD

**Issue by rickatech** [rickatech/backstage#9]
MS Office plug-in users may need to adjust their account settings.

Currently this is done by using a developer tool, which is not very friendly.
https://github.com/rickatech/backstage/wiki/User-Guide

This ticket is to track adding a button to allow users to change their settings from either MS WIndows Control Panel or MS Office plug-in popup Settings feature.

![msoffice_plug_settings_0](https://cloud.githubusercontent.com/assets/11014263/25732224/1cc2085c-3102-11e7-8dd8-3eceb364ea7c.png)

![msoffice_plug_settings_1](https://cloud.githubusercontent.com/assets/11014263/25732229/24352b96-3102-11e7-9fac-902c5b32c93c.png)

**Comment by sdn-dev** [comment]
Your proposed idea of using a Settings button in the "Open"/"Save As" backstage menu of MS Word is the right choice. It is conveniently accessible to the user and incur no jumping to another location for settings. From the development standpoint, it is coded in C# and integrates into the add-in code base (the control panel applet require native C++ coding) . 

Due to restrictions in the allowed UI design (layout, components) for an Office Add-in, the location of the settings button will be close to the textboxes we already have in place.

![Settings](https://cloud.githubusercontent.com/assets/25678596/25850043/79336b50-34de-11e7-8dd7-21e203fef1db.PNG)

The setting values are stored in the same registry location. When the Settings form is loaded, the values are read from the registry and the associated fields are populated.

Please download the v5.0 of the add-in from Dropbox: https://www.dropbox.com/sh/chzpyqvw7fysu43/AAAlueLYO2F-S6d8uy6qDYwsa?dl=0

**Comment by sdn-dev** [comment]
Also, hitting the Save button will dissolve any existing WebDAV drive connections and remap using the new credentials.

**Comment by rickatech** [comment]
Seems to work as far as I can tell.  Thanks.  

Dropbox shows two files.  I think I tested using the msi.  Are both the same plug-in, different installer?  ... do both work on Win10 and Win7?
ProLoopSetup(5.0.0).msi
ProLoopSetup(5.0.0).wixpdb

![gh_oc 19_1](https://cloud.githubusercontent.com/assets/11014263/25982450/76455f66-3691-11e7-9d8c-a23ab3a70c37.png)

**Comment by sdn-dev** [comment]
Wix is used along with Add-in Express to build the setup/installer. I believe, the .wixpdb file is optional. Both files are part of the setup. However, I haven't tested it.

Right now, we're targeting Win10 (.NET Framework 4.5). I have to re-target the same source code to .NET Framework 3.5 to support Win7.

**Comment by rickatech** [comment]
Closing this as M4 complete.
